title: Xiaoming Niu 
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>Hi! I'm Xiaoming Niu! I am currently a master's student in Computer Science at USC. My main interests lie in Full-stack Development, Android Development and Web Infrastructure in general. I am open to all internship opportunities as a software engineer.<br>
  <a> </a>
  <a href="https://www.linkedin.com/in/xiaoming-niu-164547193/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
