title: Xiaoming Niu 
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>Hi! I'm Xiaoming Niu! I am actively looking for 2021 summer SDE internships! I am currently a master's student in Computer Science at USC and my expected graduation date is Dec 2021. I have two SDE internships in both American and Chinese tech companies. My main interests lie in Full-Stack Development & Android Development. <br>
  <a> </a>
  <a href="https://www.linkedin.com/in/xiaoming-niu/">View My LinkedIn Profile</a>
  <a href="https://github.com/xiaomingniu129">View My GitHub</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
